spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gofit
    username: postgres
    password: password
    type: com.zaxxer.hikari.HikariDataSource


info:
  app:
    name: Gofit
    description: Service for fitnes center management
    version: 0.0.1

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - health